import { assertEnabledToken, enabledNetworks, enabledTokens, type SupportedNetworks } from "../config/networks.js";
import { badRequest, notFound, unprocessable } from "../errors.js";
import type { Encryptor } from "../security/encryption.js";
import { webhookEventTypes, type Merchant, type NetworkSlug, type NotificationPreferences, type OperationalWallet, type TokenSymbol, type TokenTransfer, type WebhookEvent, type WebhookEventType, type WalletTransaction, type WalletTransactionAsset } from "../types/domain.js";
import { formatTokenAmount, parseTokenAmount } from "../utils/amount.js";
import { normalizeAddress } from "../utils/address.js";
import { newId } from "../utils/id.js";
import { generateChainWallet, operationalWalletScopeKey } from "../utils/wallet.js";
import type { Repository } from "../repositories/repository.js";
import type { ChainProvider } from "../worker/chain-provider.js";
import type { DepositService } from "./deposit-service.js";
import type { SettlementService } from "./settlement-service.js";
import { publicDepositAddress, publicTreasuryTransfer, publicTreasuryWallet, publicTransfer } from "./deposit-service.js";
import { publicMerchantSettings } from "./merchant-service.js";

type Resource = "depositAddresses" | "deposits" | "treasuryTransfers" | "walletTransactions" | "gasTopUps" | "sweeps" | "webhooks";
interface HistoryInput { resource: Resource; limit: number; offset: number; status?: string; network?: NetworkSlug; token?: TokenSymbol; q?: string; }
const scanLimit = 5_000;
export class DashboardService {
  constructor(private readonly repo: Repository, private readonly encryptor: Encryptor, private readonly networks: SupportedNetworks, private readonly chainProvider: ChainProvider, private readonly settlementService: SettlementService, private readonly depositService: DepositService, private readonly ownerMerchantId: string, private readonly ownerMerchantName: string) {}
  private async merchant(): Promise<Merchant> { return await this.repo.getMerchant(this.ownerMerchantId) ?? await this.repo.createMerchant({ id: this.ownerMerchantId, name: this.ownerMerchantName, rejectDuplicateClientPendingDeposits: true }); }
  async getOverview() { const m = await this.merchant(); const [addresses, deposits, txs, webhooks, wallets] = await Promise.all([this.repo.listDepositAddresses({ merchantId: m.id, limit: 500 }), this.repo.listTransfersForMerchant(m.id, { limit: 500 }), this.repo.listWalletTransactions(200), this.repo.listWebhookEvents(200), this.repo.listOperationalWallets({ includeDisabled: false, limit: 250 })]); const ownerTxs = txs.filter((x) => x.merchantId === m.id || x.merchantId === null); const ownerWebhooks = webhooks.filter((x) => x.merchantId === m.id); return { stats: { merchants: 1, activeDepositAddresses: addresses.filter((x) => x.status === "active").length, confirmedDeposits: deposits.filter((x) => x.status === "confirmed").length, pendingWebhooks: ownerWebhooks.filter((x) => x.status === "pending").length, operationalWallets: wallets.filter((x) => x.merchantId === m.id || x.merchantId === null).length, submittedWalletTransactions: ownerTxs.filter((x) => x.status === "submitted").length }, charts: { depositTrend: buildDepositTrend(deposits), depositStatus: countBy(deposits, (x) => x.status), tokenVolume: buildTokenVolume(deposits), walletTransactionStatus: countBy(ownerTxs, (x) => x.status), webhookStatus: countBy(ownerWebhooks, (x) => x.status) }, recentDeposits: deposits.slice(0, 12).map(publicTransfer), recentWalletTransactions: ownerTxs.slice(0, 12).map(publicWalletTransaction), recentWebhooks: ownerWebhooks.slice(0, 12).map(publicWebhookEvent) }; }
  async listDashboardData(limit: number) { const m = await this.merchant(); const [apiKeys, webhookConfig, prefs, treasuryWallets, operationalWallets, addresses, deposits, treasuryTransfers, gas, sweeps, txs, webhooks] = await Promise.all([this.repo.listApiKeys(m.id, limit), this.repo.getWebhookConfig(m.id), this.repo.getNotificationPreferences(m.id), this.repo.listTreasuryWallets({ merchantId: m.id, limit }), this.repo.listOperationalWallets({ includeDisabled: false, limit }), this.repo.listDepositAddresses({ merchantId: m.id, limit }), this.repo.listTransfersForMerchant(m.id, { limit }), this.repo.listTreasuryTransfers({ merchantId: m.id, limit }), this.repo.listGasTopUps(limit), this.repo.listSweeps(limit), this.repo.listWalletTransactions(limit), this.repo.listWebhookEvents(limit)]); return { merchants: [publicMerchantSettings(m)], settings: publicMerchantSettings(m), apiKeys: apiKeys.map((k) => ({ id: k.id, merchantId: k.merchantId, publicKey: k.publicKey, status: k.status, createdAt: k.createdAt.toISOString(), lastUsedAt: k.lastUsedAt?.toISOString() ?? null })), webhookConfig: webhookConfig ? { merchantId: webhookConfig.merchantId, url: webhookConfig.url, active: webhookConfig.active, createdAt: webhookConfig.createdAt.toISOString(), updatedAt: webhookConfig.updatedAt.toISOString() } : null, notificationPreferences: publicPrefs(prefs, m.id), networks: enabledNetworks(this.networks).map((n) => ({ network: n.slug, kind: n.kind, chainId: n.chainId ?? null, confirmations: n.confirmations, tokens: enabledTokens(n).map((t) => ({ symbol: t.symbol, contractAddress: t.contractAddress, decimals: t.decimals })) })), treasuryWallets: treasuryWallets.map(publicTreasuryWallet), operationalWallets: operationalWallets.filter((x) => x.merchantId === m.id || x.merchantId === null).map(publicOperationalWallet), depositAddresses: addresses.map(publicDepositAddress), deposits: deposits.map(publicTransfer), treasuryTransfers: treasuryTransfers.map(publicTreasuryTransfer), gasTopUps: gas.filter((x) => x.merchantId === m.id).map(publicGasTopUp), sweeps: sweeps.filter((x) => x.merchantId === m.id).map(publicSweep), walletTransactions: txs.filter((x) => x.merchantId === m.id || x.merchantId === null).map(publicWalletTransaction), webhooks: webhooks.filter((x) => x.merchantId === m.id).map(publicWebhookEvent) }; }
  async updateNotificationPreferences(enabledEvents: WebhookEventType[]) { const m = await this.merchant(); return publicPrefs(await this.repo.upsertNotificationPreferences({ merchantId: m.id, enabledEvents: [...new Set(enabledEvents)] }), m.id); }
  async getHistory(input: HistoryInput) { await this.merchant(); const rows = await this.rows(input.resource); const filtered = rows.filter((r) => (!input.status || String(r.status ?? "") === input.status) && (!input.network || String(r.network ?? "") === input.network) && (!input.token || String(r.token ?? "") === input.token) && (!input.q || Object.values(r).some((v) => typeof v === "string" && v.toLowerCase().includes(input.q!.toLowerCase())))); return { resource: input.resource, limit: input.limit, offset: input.offset, total: filtered.length, nextOffset: input.offset + input.limit < filtered.length ? input.offset + input.limit : null, previousOffset: input.offset > 0 ? Math.max(0, input.offset - input.limit) : null, items: filtered.slice(input.offset, input.offset + input.limit) }; }
  async generateGasWallet(input: { network: NetworkSlug; label?: string }) { const n = this.networks[input.network]; if (!n) throw badRequest("unsupported_network", `${input.network} is not enabled`); const generated = await generateChainWallet(n.kind); return publicOperationalWallet(await this.repo.upsertOperationalWallet({ id: newId(), scopeKey: operationalWalletScopeKey("gas", null, n.slug, null), merchantId: null, purpose: "gas", network: n.slug, token: null, address: normalizeAddress(n, generated.address), privateKeyEncrypted: this.encryptor.encryptString(generated.privateKey), label: input.label ?? `${n.slug} gas wallet` })); }
  async generateTreasuryWallet(input: { network: NetworkSlug; token: TokenSymbol; label?: string }) { const m = await this.merchant(); const { network } = assertEnabledToken(this.networks, input.network, input.token); const generated = await generateChainWallet(network.kind); const id = newId(); const label = input.label ?? `${m.name} ${network.slug} ${input.token} treasury`; const op = await this.repo.upsertOperationalWallet({ id, scopeKey: `${operationalWalletScopeKey("treasury", m.id, network.slug, input.token)}:${id}`, merchantId: m.id, purpose: "treasury", network: network.slug, token: input.token, address: normalizeAddress(network, generated.address), privateKeyEncrypted: this.encryptor.encryptString(generated.privateKey), label }); const tw = await this.repo.upsertTreasuryWallet({ id: newId(), merchantId: m.id, network: network.slug, token: input.token, address: op.address, label, operationalWalletId: op.id }); return { operationalWallet: publicOperationalWallet(op), treasuryWallet: publicTreasuryWallet(tw) }; }
  async registerTreasuryWallet(input: { network: NetworkSlug; token: TokenSymbol; address: string; label?: string }) { const m = await this.merchant(); const { network } = assertEnabledToken(this.networks, input.network, input.token); return publicTreasuryWallet(await this.repo.upsertTreasuryWallet({ id: newId(), merchantId: m.id, network: network.slug, token: input.token, address: normalizeAddress(network, input.address), label: input.label ?? `${m.name} ${network.slug} ${input.token} treasury`, operationalWalletId: null })); }
  async setDefaultTreasuryWallet(id: string) { const m = await this.merchant(); const wallet = await this.repo.setDefaultTreasuryWallet(m.id, id); if (!wallet) throw notFound("treasury_wallet_not_found", "Treasury wallet was not found"); return publicTreasuryWallet(wallet); }
  async retryDepositSettlement(id: string) { const m = await this.merchant(); const transfer = await this.repo.getTokenTransfer(id); if (!transfer || transfer.merchantId !== m.id) throw notFound("deposit_not_found", "Deposit transfer was not found"); if (transfer.status !== "confirmed" && transfer.status !== "late") throw unprocessable("deposit_not_ready", "Only confirmed or late deposits can be settled"); await this.settlementService.ensureSettlement(transfer, { forceRetry: true }); return publicTransfer(await this.repo.getTokenTransfer(id) ?? transfer); }
  async closeDepositAddress(id: string) { const m = await this.merchant(); return this.depositService.closeDepositAddress(m.id, id); }
  async matchTreasuryTransfer(tid: string, did: string) { const m = await this.merchant(); return this.depositService.matchTreasuryTransfer(m.id, tid, did); }
  async createWalletTransaction(input: { sourceWalletId: string; asset: WalletTransactionAsset; toAddress: string; amount: string }) { const source = await this.repo.getOperationalWallet(input.sourceWalletId); if (!source || source.status !== "active") throw notFound("source_wallet_not_found", "Source wallet was not found"); const network = this.networks[source.network]; if (!network) throw badRequest("unsupported_network", `${source.network} is not enabled`); const amount = parseDashboardAmount(input.amount, input.asset === "NATIVE" ? nativeDecimals(network.kind) : assertEnabledToken(this.networks, source.network, input.asset).token.decimals); const toAddress = normalizeAddress(network, input.toAddress); const token = input.asset === "NATIVE" ? null : assertEnabledToken(this.networks, source.network, input.asset).token; const txInput = { id: newId(), merchantId: source.merchantId, sourceWalletId: source.id, network: source.network, token: input.asset === "NATIVE" ? null : input.asset, asset: input.asset, txHash: null, fromAddress: source.address, toAddress, amountRaw: amount.toString(), amountFormatted: formatTokenAmount(amount, input.asset === "NATIVE" ? nativeDecimals(network.kind) : token!.decimals) }; try { const txHash = input.asset === "NATIVE" ? await this.chainProvider.sendNativeTransfer(network, this.encryptor.decryptString(source.privateKeyEncrypted), toAddress, amount) : await this.chainProvider.sendTokenTransfer(network, token!, this.encryptor.decryptString(source.privateKeyEncrypted), toAddress, amount); return publicWalletTransaction(await this.repo.createWalletTransaction({ ...txInput, txHash, status: "submitted" })); } catch (e) { const failureReason = e instanceof Error ? e.message : "Wallet transaction failed"; const transaction = await this.repo.createWalletTransaction({ ...txInput, status: "failed", failureReason }); throw unprocessable("wallet_transaction_failed", "Wallet transaction failed", publicWalletTransaction(transaction)); } }
  private async rows(resource: Resource): Promise<Array<Record<string, unknown>>> { const m = await this.merchant(); switch (resource) { case "depositAddresses": return (await this.repo.listDepositAddresses({ merchantId: m.id, limit: scanLimit })).map(publicDepositAddress); case "deposits": return (await this.repo.listTransfersForMerchant(m.id, { limit: scanLimit })).map(publicTransfer); case "treasuryTransfers": return (await this.repo.listTreasuryTransfers({ merchantId: m.id, limit: scanLimit })).map(publicTreasuryTransfer); case "walletTransactions": return (await this.repo.listWalletTransactions(scanLimit)).filter((x) => x.merchantId === m.id || x.merchantId === null).map(publicWalletTransaction); case "gasTopUps": return (await this.repo.listGasTopUps(scanLimit)).filter((x) => x.merchantId === m.id).map(publicGasTopUp); case "sweeps": return (await this.repo.listSweeps(scanLimit)).filter((x) => x.merchantId === m.id).map(publicSweep); case "webhooks": return (await this.repo.listWebhookEvents(scanLimit)).filter((x) => x.merchantId === m.id).map(publicWebhookEvent); } }
}
function nativeDecimals(kind: "evm" | "tron") { return kind === "tron" ? 6 : 18; }
function parseDashboardAmount(amount: string, decimals: number) { const [, fractional = ""] = amount.split("."); if (fractional.length > decimals) throw badRequest("invalid_amount", `Amount must fit the asset decimal precision of ${decimals}`); const raw = parseTokenAmount(amount, decimals); if (raw <= 0n) throw badRequest("invalid_amount", "Amount must be greater than zero"); return raw; }
function publicPrefs(p: NotificationPreferences | null, merchantId: string) { return { merchantId, enabledEvents: p?.enabledEvents ?? [...webhookEventTypes], createdAt: p?.createdAt.toISOString() ?? null, updatedAt: p?.updatedAt.toISOString() ?? null }; }
function publicOperationalWallet(w: OperationalWallet) { return { id: w.id, merchantId: w.merchantId, purpose: w.purpose, network: w.network, token: w.token, address: w.address, label: w.label, status: w.status, hasStoredPrivateKey: true, createdAt: w.createdAt.toISOString(), updatedAt: w.updatedAt.toISOString() }; }
function publicWalletTransaction(t: WalletTransaction) { return { id: t.id, merchantId: t.merchantId, sourceWalletId: t.sourceWalletId, network: t.network, token: t.token, asset: t.asset, txHash: t.txHash, fromAddress: t.fromAddress, toAddress: t.toAddress, amountRaw: t.amountRaw, amountFormatted: t.amountFormatted, status: t.status, failureReason: t.failureReason, createdAt: t.createdAt.toISOString(), confirmedAt: t.confirmedAt?.toISOString() ?? null }; }
function publicGasTopUp(x: { id: string; merchantId: string; transferId: string; depositAddressId: string; network: NetworkSlug; txHash: string | null; amountWei: string; attemptNumber: number; status: string; failureReason: string | null; createdAt: Date; confirmedAt: Date | null; }) { return { id: x.id, merchantId: x.merchantId, transferId: x.transferId, depositAddressId: x.depositAddressId, network: x.network, txHash: x.txHash, amountWei: x.amountWei, attemptNumber: x.attemptNumber, status: x.status, failureReason: x.failureReason, createdAt: x.createdAt.toISOString(), confirmedAt: x.confirmedAt?.toISOString() ?? null }; }
function publicSweep(x: { id: string; merchantId: string; transferId: string; depositAddressId: string; network: NetworkSlug; token: TokenSymbol; txHash: string | null; amountRaw: string; amountFormatted: string; toAddress: string; attemptNumber: number; status: string; failureReason: string | null; createdAt: Date; confirmedAt: Date | null; }) { return { id: x.id, merchantId: x.merchantId, transferId: x.transferId, depositAddressId: x.depositAddressId, network: x.network, token: x.token, txHash: x.txHash, amountRaw: x.amountRaw, amountFormatted: x.amountFormatted, toAddress: x.toAddress, attemptNumber: x.attemptNumber, status: x.status, failureReason: x.failureReason, createdAt: x.createdAt.toISOString(), confirmedAt: x.confirmedAt?.toISOString() ?? null }; }
function publicWebhookEvent(e: WebhookEvent) { return { id: e.id, merchantId: e.merchantId, depositAddressId: e.depositAddressId, type: e.type, url: e.url, payload: e.payload, status: e.status, attempts: e.attempts, lastError: e.lastError, responseStatus: e.responseStatus, createdAt: e.createdAt.toISOString(), updatedAt: e.updatedAt.toISOString(), nextAttemptAt: e.nextAttemptAt.toISOString(), sentAt: e.sentAt?.toISOString() ?? null }; }
function buildDepositTrend(deposits: TokenTransfer[]) { const buckets = new Map<string, { date: string; count: number; confirmedCount: number; amount: number }>(); const now = new Date(); for (let i = 13; i >= 0; i -= 1) { const d = new Date(now); d.setUTCDate(now.getUTCDate() - i); const key = d.toISOString().slice(0, 10); buckets.set(key, { date: key, count: 0, confirmedCount: 0, amount: 0 }); } for (const dep of deposits) { const key = dep.detectedAt.toISOString().slice(0, 10); const b = buckets.get(key); if (!b) continue; b.count += 1; if (dep.status === "confirmed") b.confirmedCount += 1; b.amount += Number.parseFloat(dep.amountFormatted) || 0; } return [...buckets.values()]; }
function buildTokenVolume(deposits: TokenTransfer[]) { return countBy(deposits.filter((d) => d.status === "confirmed"), (d) => `${d.network} ${d.token}`).map((x) => ({ asset: x.name, amount: 0, count: x.value })); }
function countBy<T>(items: T[], key: (item: T) => string) { const m = new Map<string, { name: string; value: number }>(); for (const item of items) { const k = key(item); const v = m.get(k) ?? { name: k, value: 0 }; v.value += 1; m.set(k, v); } return [...m.values()]; }
