import type { SupportedNetworks } from "../config/networks.js";
import type { Encryptor } from "../security/encryption.js";
import type { GasTopUp, NetworkSlug, Sweep, TokenTransfer } from "../types/domain.js";
import { formatTokenAmount } from "../utils/amount.js";
import { normalizeAddress } from "../utils/address.js";
import { newId } from "../utils/id.js";
import { privateKeyToChainAddress } from "../utils/wallet.js";
import type { Repository } from "../repositories/repository.js";
import type { ChainProvider } from "../worker/chain-provider.js";
import { publicTransfer } from "./deposit-service.js";
import type { WebhookService } from "./webhook-service.js";
export interface SettlementServiceDependencies { repo: Repository; networks: SupportedNetworks; encryptor: Encryptor; chainProvider: ChainProvider; webhooks: WebhookService; }
export class SettlementService {
  constructor(private readonly deps: SettlementServiceDependencies) {}
  async ensureSettlement(transfer: TokenTransfer, options: { forceRetry?: boolean } = {}): Promise<void> {
    if (transfer.settlementStatus === "settled" || (transfer.settlementStatus === "submitted" && !options.forceRetry)) return;
    const deposit = await this.deps.repo.getDepositAddressForMerchant(transfer.merchantId, transfer.depositAddressId);
    if (!deposit) return this.markSettlementFailure(transfer.id, null, "Deposit address was not found");
    if (deposit.flow === "direct_treasury") return void await this.deps.repo.updateTransferSettlement(transfer.id, { settlementStatus: "settled", settlementStep: null, settlementFailureReason: null });
    if (!deposit.privateKeyEncrypted) return this.markSettlementFailure(transfer.id, null, "Deposit wallet private key is not stored");
    const network = this.deps.networks[transfer.network]; const token = network?.tokens[transfer.token];
    if (!network || !token) return this.markSettlementFailure(transfer.id, null, "Network or token is not enabled");
    const nativeBalance = await this.deps.chainProvider.getNativeBalance(network, deposit.address);
    if (nativeBalance < network.minGasWei) return this.submitGasTopUp(transfer, deposit.id, deposit.address);
    const treasury = deposit.treasuryWalletId ? await this.deps.repo.getTreasuryWalletById(transfer.merchantId, deposit.treasuryWalletId) : await this.deps.repo.getTreasuryWallet(transfer.merchantId, transfer.network, transfer.token);
    if (!treasury) return this.markSettlementFailure(transfer.id, "sweep", "Treasury wallet was not found");
    const tokenBalance = await this.deps.chainProvider.getTokenBalance(network, token, deposit.address);
    if (tokenBalance <= 0n) return this.markSettlementFailure(transfer.id, "sweep", "Deposit wallet token balance is zero");
    const attemptNumber = ((await this.deps.repo.getLatestSweepByTransfer(transfer.id))?.attemptNumber ?? 0) + 1;
    try {
      const txHash = await this.deps.chainProvider.sendTokenTransfer(network, token, this.deps.encryptor.decryptString(deposit.privateKeyEncrypted), treasury.address, tokenBalance);
      const sweep = await this.deps.repo.createSweep({ id: newId(), transferId: transfer.id, merchantId: transfer.merchantId, depositAddressId: deposit.id, network: transfer.network, token: transfer.token, txHash, amountRaw: tokenBalance.toString(10), amountFormatted: formatTokenAmount(tokenBalance, token.decimals), toAddress: treasury.address, attemptNumber, status: "submitted" });
      await this.deps.repo.updateTransferSettlement(transfer.id, { settlementStatus: "submitted", settlementStep: "sweep", settlementFailureReason: null });
      await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, "sweep.submitted", { transfer: publicTransfer(transfer), sweep: publicSweep(sweep) }, { depositAddressId: deposit.id });
    } catch (error) {
      const failureReason = error instanceof Error ? error.message : "Sweep transaction failed";
      const sweep = await this.deps.repo.createSweep({ id: newId(), transferId: transfer.id, merchantId: transfer.merchantId, depositAddressId: deposit.id, network: transfer.network, token: transfer.token, txHash: null, amountRaw: tokenBalance.toString(10), amountFormatted: formatTokenAmount(tokenBalance, token.decimals), toAddress: treasury.address, attemptNumber, status: "failed", failureReason });
      await this.markSettlementFailure(transfer.id, "sweep", failureReason);
      await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, "sweep.failed", { transfer: publicTransfer(transfer), sweep: publicSweep(sweep) }, { depositAddressId: deposit.id });
    }
  }
  async confirmGasTopUps() { for (const topUp of await this.deps.repo.listSubmittedGasTopUps(100)) { if (!topUp.txHash) continue; const network = this.deps.networks[topUp.network]; if (!network) continue; const receipt = await this.deps.chainProvider.getTransactionReceipt(network, topUp.txHash); if (!receipt) continue; const success = receipt.status === "success"; const updated = await this.deps.repo.updateGasTopUpStatus(topUp.id, success ? "confirmed" : "failed", topUp.txHash, success ? null : "Gas top-up transaction reverted"); const transfer = await this.deps.repo.getTokenTransfer(topUp.transferId); if (!transfer) continue; await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, success ? "gas.topup.confirmed" : "gas.topup.failed", { transfer: publicTransfer(transfer), gasTopUp: publicGasTopUp(updated ?? topUp) }, { depositAddressId: topUp.depositAddressId }); if (success) { await this.deps.repo.updateTransferSettlement(transfer.id, { settlementStatus: "pending", settlementStep: "sweep", settlementFailureReason: null }); await this.ensureSettlement(await this.deps.repo.getTokenTransfer(transfer.id) ?? transfer, { forceRetry: true }); } else await this.markSettlementFailure(transfer.id, "gas_top_up", "Gas top-up transaction reverted"); } }
  async confirmSweeps() { for (const sweep of await this.deps.repo.listSubmittedSweeps(100)) { if (!sweep.txHash) continue; const network = this.deps.networks[sweep.network]; if (!network) continue; const receipt = await this.deps.chainProvider.getTransactionReceipt(network, sweep.txHash); if (!receipt) continue; const success = receipt.status === "success"; const updated = await this.deps.repo.updateSweepStatus(sweep.id, success ? "confirmed" : "failed", sweep.txHash, success ? null : "Sweep transaction reverted"); const transfer = await this.deps.repo.getTokenTransfer(sweep.transferId); if (!transfer) continue; if (success) await this.deps.repo.updateTransferSettlement(transfer.id, { settlementStatus: "settled", settlementStep: null, settlementFailureReason: null }); else await this.markSettlementFailure(transfer.id, "sweep", "Sweep transaction reverted"); await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, success ? "sweep.confirmed" : "sweep.failed", { transfer: publicTransfer(await this.deps.repo.getTokenTransfer(transfer.id) ?? transfer), sweep: publicSweep(updated ?? sweep) }, { depositAddressId: sweep.depositAddressId }); } }
  private async submitGasTopUp(transfer: TokenTransfer, depositAddressId: string, toAddress: string) { const network = this.deps.networks[transfer.network]; if (!network) return this.markSettlementFailure(transfer.id, "gas_top_up", "Network is not enabled"); const attemptNumber = ((await this.deps.repo.getLatestGasTopUpByTransfer(transfer.id))?.attemptNumber ?? 0) + 1; const gasPrivateKey = await this.resolveGasPrivateKey(transfer.network); if (!gasPrivateKey) {
      const topUp = await this.deps.repo.createGasTopUp({ id: newId(), transferId: transfer.id, merchantId: transfer.merchantId, depositAddressId, network: transfer.network, txHash: null, amountWei: network.gasTopUpWei.toString(10), attemptNumber, status: "failed", failureReason: "Gas wallet was not found" });
      await this.markSettlementFailure(transfer.id, "gas_top_up", "Gas wallet was not found");
      await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, "gas.topup.failed", { transfer: publicTransfer(transfer), gasTopUp: publicGasTopUp(topUp) }, { depositAddressId });
      return;
    } try { const txHash = await this.deps.chainProvider.sendNativeTransfer(network, gasPrivateKey, toAddress, network.gasTopUpWei); const topUp = await this.deps.repo.createGasTopUp({ id: newId(), transferId: transfer.id, merchantId: transfer.merchantId, depositAddressId, network: transfer.network, txHash, amountWei: network.gasTopUpWei.toString(10), attemptNumber, status: "submitted" }); await this.deps.repo.updateTransferSettlement(transfer.id, { settlementStatus: "submitted", settlementStep: "gas_top_up", settlementFailureReason: null }); await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, "gas.topup.submitted", { transfer: publicTransfer(transfer), gasTopUp: publicGasTopUp(topUp) }, { depositAddressId }); } catch (error) { const failureReason = error instanceof Error ? error.message : "Gas top-up transaction failed"; const topUp = await this.deps.repo.createGasTopUp({ id: newId(), transferId: transfer.id, merchantId: transfer.merchantId, depositAddressId, network: transfer.network, txHash: null, amountWei: network.gasTopUpWei.toString(10), attemptNumber, status: "failed", failureReason }); await this.markSettlementFailure(transfer.id, "gas_top_up", failureReason); await this.deps.webhooks.enqueueMerchantEvent(transfer.merchantId, "gas.topup.failed", { transfer: publicTransfer(transfer), gasTopUp: publicGasTopUp(topUp) }, { depositAddressId }); } }
  private async resolveGasPrivateKey(networkSlug: NetworkSlug) { const network = this.deps.networks[networkSlug]; if (!network) return null; if (network.gasWalletPrivateKey) return network.gasWalletPrivateKey; const wallet = await this.deps.repo.getOperationalGasWallet(networkSlug); if (!wallet || wallet.status !== "active") return null; const privateKey = this.deps.encryptor.decryptString(wallet.privateKeyEncrypted); void normalizeAddress; void privateKeyToChainAddress; return privateKey; }
  private async markSettlementFailure(transferId: string, step: "gas_top_up" | "sweep" | null, failureReason: string) { await this.deps.repo.updateTransferSettlement(transferId, { settlementStatus: "pending", settlementStep: step, settlementFailureReason: failureReason }); }
}
function publicGasTopUp(topUp: GasTopUp) { return { id: topUp.id, merchantId: topUp.merchantId, transferId: topUp.transferId, depositAddressId: topUp.depositAddressId, network: topUp.network, txHash: topUp.txHash, amountWei: topUp.amountWei, attemptNumber: topUp.attemptNumber, status: topUp.status, failureReason: topUp.failureReason, createdAt: topUp.createdAt.toISOString(), confirmedAt: topUp.confirmedAt?.toISOString() ?? null }; }
function publicSweep(sweep: Sweep) { return { id: sweep.id, merchantId: sweep.merchantId, transferId: sweep.transferId, depositAddressId: sweep.depositAddressId, network: sweep.network, token: sweep.token, txHash: sweep.txHash, amountRaw: sweep.amountRaw, amountFormatted: sweep.amountFormatted, toAddress: sweep.toAddress, attemptNumber: sweep.attemptNumber, status: sweep.status, failureReason: sweep.failureReason, createdAt: sweep.createdAt.toISOString(), confirmedAt: sweep.confirmedAt?.toISOString() ?? null }; }
